# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8038b9f5cb2ad1892edff610485d1946a08dd8744495a515fd0f7a9fff672cf6a64ca03ec90dce56c52c4cc11a24d33e0644f23ac2f82b5de75e2d96195ba5c9

test:
  secret_key_base: c59b688718e0a0730b23ba501572eaedf454a1a687eca28c0c3116a5f30091c95ec12007cf7b779d717a40e31a70ae53a45cabe1070f11f761bd547f88f08e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
